---
- name: 'Install a few pre-requisite packages'
  apt:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - 'unrar'
    - 'unzip'
    - 'tar'
    - 'p7zip'

- name: 'Create the user that the sabnzb daemon will run as'
  user:
    name: "{{ sabnzbd_daemon_user }}"

- name: 'Create the sabnzbd application directory'
  file:
    path: "{{ sabnzbd_app_directory }}"
    state: 'directory'
    owner: "{{ sabnzbd_daemon_user }}"
    mode: '0755'

- name: 'Create the sabnzbd data directories'
  file:
    path: "{{ sabnzbd_app_directory }}/{{ item }}"
    state: 'directory'
    owner: "{{ sabnzbd_daemon_user }}"
    mode: '0755'
  with_items:
    - 'config'
    - 'downloads'
    - 'incomplete-downloads'

- name: 'Create the sabnzbd config directory only if it is not already present'
  shell: '/bin/mkdir -p {{ sabnzbd_daemon_config_file | dirname }} && /bin/chown -R {{ sabnzbd_daemon_user }}: {{ sabnzbd_daemon_config_file | dirname }}'
  args:
    creates: '{{ sabnzbd_daemon_config_file | dirname }}'

- name: 'Set the contents of the /etc/default/sabnzbdplus file appropriately'
  template:
    src: 'sabnzbdplus.j2'
    dest: '/etc/default/sabnzbdplus'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'restart-ansible-role-sabnzbd'

- name: 'Add the stable sabnzbd PPA repository'
  apt_repository:
    repo: 'ppa:jcfp/nobetas'
    state: 'present'
    update_cache: 'yes'

- name: 'Install the latest stable version of sabnzbd'
  apt:
    name: 'sabnzbdplus'
    state: 'latest'
  notify: 'restart-ansible-role-sabnzbd'

- meta: flush_handlers

- name: 'Ensure that the sabnzbd daemon is running'
  service:
    name: 'sabnzbdplus'
    state: 'started'
    enabled: 'yes'

- name: 'Create the nzbtomedia scripts directory'
  file:
    path: "{{ sabnzbd_nzbtomedia_directory }}"
    state: 'directory'
    owner: "{{ sabnzbd_daemon_user }}"
    mode: '0755'

- name: 'Git clone the nzbtomedia scripts locally'
  git:
    clone: 'yes'
    dest: "{{ sabnzbd_nzbtomedia_directory }}"
    force: 'yes'
    repo: 'https://github.com/clinton-hall/nzbToMedia.git'
    version: '2d770510a284fadc6b44628626f5769789086dbb'  # SHA corresponding to v10.15

- name: 'Put the autoProcessMedia.cfg file in place'
  copy:
    content: "{{ sabnzbd_nzbtomedia_autoprocessmedia_cfg }}"
    dest: "{{ sabnzbd_nzbtomedia_directory }}/autoProcessMedia.cfg"
    mode: '0644'
